"use client";
import { useEffect, useState } from "react";
import { useNav } from "@/lib/nav-context";
import { ArrowLeft, Check, CheckCheck, Edit3 } from "lucide-react";
const { useToast } = require("@/hooks/use-toast");
interface Field { id: string; field_name: string; field_value: string; confidence_score: number; verified_by_user: boolean; source_snippet: string | null; }
export default function DocumentVerifyContent() {
  const { params, navigate } = useNav(); const docId = params.id as string; const { toast } = useToast();
  const [fields, setFields] = useState<Field[]>([]); const [loading, setLoading] = useState(true); const [editingId, setEditingId] = useState<string | null>(null); const [editValue, setEditValue] = useState("");
  useEffect(() => { if (!docId) return; const t = localStorage.getItem("finsight_token"); fetch(`/api/extraction/${docId}/fields`, { headers: { Authorization: `Bearer ${t}` } }).then(r => r.json()).then(d => setFields(d.items || [])).finally(() => setLoading(false)); }, [docId]);
  const verify = async (id: string) => { const t = localStorage.getItem("finsight_token"); try { await fetch(`/api/extraction/${docId}/fields/${id}/verify`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${t}` }, body: JSON.stringify({}) }); setFields(fs => fs.map(f => f.id === id ? { ...f, verified_by_user: true, confidence_score: 1.0 } : f)); toast({ title: "Verified!" }); } catch {} };
  const verifyAll = async () => { const t = localStorage.getItem("finsight_token"); try { await fetch(`/api/extraction/${docId}/verify-all`, { method: "POST", headers: { Authorization: `Bearer ${t}` } }); setFields(fs => fs.map(f => ({ ...f, verified_by_user: true, confidence_score: 1.0 }))); toast({ title: "All verified!" }); } catch {} };
  const edit = async (id: string) => { const t = localStorage.getItem("finsight_token"); try { await fetch(`/api/extraction/${docId}/fields/${id}/verify`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${t}` }, body: JSON.stringify({ value: editValue }) }); setFields(fs => fs.map(f => f.id === id ? { ...f, field_value: editValue, verified_by_user: true, confidence_score: 1.0 } : f)); setEditingId(null); toast({ title: "Updated & verified!" }); } catch {} };
  if (loading) return <div className="skeleton h-96 rounded-2xl" />;
  return (
    <div className="space-y-5 animate-fade-in">
      <div className="flex items-center gap-3 animate-slide-up"><button onClick={() => navigate("documents")} className="p-1.5 rounded-lg transition-colors" style={{ color: "var(--color-ink-muted)" }}><ArrowLeft className="h-4 w-4" /></button><div><p className="text-caption mb-1">Review</p><h1 className="text-heading">Verify Extracted Fields</h1></div></div>
      {fields.length === 0 ? <div className="bento bento-light p-12 text-center"><p className="text-lg font-medium" style={{ color: "var(--color-ink)" }}>No fields extracted</p><p className="text-sm mt-1" style={{ color: "var(--color-ink-muted)" }}>This document may not contain recognizable financial data.</p></div> :
      <><div className="flex justify-end animate-slide-up stagger-1"><button onClick={verifyAll} className="h-9 px-4 rounded-lg text-sm font-medium flex items-center gap-1.5" style={{ background: "var(--color-forest)", color: "var(--color-cream)" }}><CheckCheck className="h-4 w-4" />Verify All</button></div>
      <div className="bento bento-light divide-y animate-slide-up stagger-2" style={{ borderColor: "var(--color-line-soft)" }}>
        {fields.map(f => <div key={f.id} className="flex items-center gap-4 p-4 transition-colors" style={{ borderBottom: "1px solid var(--color-line-soft)" }}>
          <div className="w-36 flex-shrink-0"><p className="text-sm font-medium capitalize" style={{ color: "var(--color-ink)" }}>{f.field_name.replace(/_/g, " ")}</p><span className="text-[10px] font-semibold uppercase px-1.5 py-0.5 rounded mt-1 inline-block" style={{ background: f.confidence_score >= 0.9 ? "rgba(13,59,46,0.08)" : f.confidence_score >= 0.7 ? "rgba(212,160,23,0.1)" : "rgba(198,93,58,0.1)", color: f.confidence_score >= 0.9 ? "var(--color-forest)" : f.confidence_score >= 0.7 ? "var(--color-gold)" : "var(--color-clay)" }}>{Math.round(f.confidence_score * 100)}%</span></div>
          <div className="flex-1">{editingId === f.id ? <div className="flex gap-2"><input value={editValue} onChange={e => setEditValue(e.target.value)} className="flex-1 h-9 rounded-lg border px-3 text-sm outline-none" style={{ borderColor: "var(--color-forest)" }} autoFocus /><button onClick={() => edit(f.id)} className="h-9 px-3 rounded-lg text-xs font-medium" style={{ background: "var(--color-forest)", color: "var(--color-cream)" }}>Save</button><button onClick={() => setEditingId(null)} className="h-9 px-3 rounded-lg text-xs font-medium" style={{ border: "1px solid var(--color-line)" }}>Cancel</button></div> : <><p className="text-sm font-mono" style={{ color: f.verified_by_user ? "var(--color-forest)" : "var(--color-ink)" }}>{f.field_value}</p>{f.source_snippet && !f.verified_by_user && <p className="text-xs mt-1 italic truncate" style={{ color: "var(--color-ink-muted)" }}>Source: "{f.source_snippet}"</p>}</>}</div>
          <div className="flex items-center gap-2">{f.verified_by_user ? <span className="text-[10px] font-bold uppercase flex items-center gap-1 px-2 py-0.5 rounded" style={{ background: "rgba(13,59,46,0.08)", color: "var(--color-forest)" }}><Check className="h-3 w-3" />Verified</span> : <><button onClick={() => { setEditingId(f.id); setEditValue(f.field_value); }} className="p-1.5 rounded-lg transition-colors" style={{ color: "var(--color-ink-muted)" }}><Edit3 className="h-3.5 w-3.5" /></button><button onClick={() => verify(f.id)} className="h-8 px-3 rounded-lg text-xs font-medium" style={{ border: "1px solid var(--color-line)", color: "var(--color-ink-soft)" }}>Verify</button></>}</div>
        </div>)}
      </div></>}
    </div>
  );
}
